name: rocLv's home for ruby & rails
description: All about ruby and rails
meta_description: "ruby or rails news, or some site developing stuff"

highlighter: rouge
logo: false
gems: ['jekyll-paginate']
paginate: 15
baseurl: /
domain_name: 'http://roclv.github.io'
google_analytics: 'UA-71237400-1'
excerpt_separator: <!--more-->
# Details for the RSS feed generator
url:            'roclv.github.io/rss'
author:         'rocLv'
